services:
  postgres-usuarios:
    image: postgres:16
    environment:
      POSTGRES_DB: fiapx_usuarios
      POSTGRES_USER: fiapx
      POSTGRES_PASSWORD: fiapx
    ports:
      - "5432:5432"
    volumes:
      - fiapx_usuarios:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fiapx -d fiapx_usuarios"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  fiapx_usuarios:
