global:
  scrape_interval: 15s

scrape_configs:
  - job_name: auth
    static_configs:
      - targets: ["auth:8080"]

  - job_name: video
    static_configs:
      - targets: ["video:8080"]

  - job_name: postgres-usuarios
    static_configs:
      - targets: ["postgres-exporter-usuarios:9187"]

  - job_name: postgres-videos
    static_configs:
      - targets: ["postgres-exporter-videos:9187"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: minio-bucket
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
      - targets: ["minio:9000"]

  - job_name: rabbitmq
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ["rabbitmq:15692"]
